
import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "AuNguyen",
      email: "AuNguyen@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "NghiaTran",
      email: "NghiaTran@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
  ],
  products: [
    {
      name: "Jacket Stussy Shirt",
      category: "Shirts",
      image: "/images/04.jpg",
      price: 3200000,
      countInStock: 10,
      brand: "Stussy",
      rating: 5,
      numReviews: 10,
      description: "high quality product",
      quanSold: 5,
      size: ["XL", "L", "M", "S"],
      discount: 10,
      colors: [ "black"],
    },
    {
      name: "Stussy Shirt",
      category: "Shirts",
      image: "/images/05.jpg",
      price: 1200000,
      countInStock: 30,
      brand: "Stussy",
      rating: 4.5,
      numReviews: 40,
      description: "high quality product",
      quanSold: 15,
      size: ["XL", "L", "M", "S"],
      discount: 10,
      colors: ["red", "black", "blue", "grey"],
    },
    {
      name: "FOG Shirt",
      category: "Shirts",
      image: "/images/06.jpg",
      price: 2200000,
      countInStock: 30,
      brand: "FOG",
      rating: 4.5,
      description: "high quality product",
      quanSold: 55,
      size: ["XL", "L", "M", "S"],
      numReviews: 14,
      discount: 10,
      colors: ["red", "black", "blue", "grey"],
    },
    {
      name: "Drew Pants",
      category: "Pants",
      image: "/images/07.jpg",
      price: 3000000,
      countInStock: 90,
      brand: "Drew",
      rating: 4,
      numReviews: 23,
      description: "high quality product",
      quanSold: 75,
      size: ["XL", "L", "M", "S"],
      discount: 10,
      colors: ["red", "black", "blue", "grey"],
    },
    {
      name: "Stussy pant",
      category: "Pants",
      image: "/images/08.jpg",
      price: 2400000,
      countInStock: 50,
      brand: "Stussy",
      rating: 4,
      numReviews: 20,
      description: "high quality product",
      quanSold: 5,
      size: ["XL", "L", "M", "S"],
      discount: 10,
      colors: ["red", "black"],
    },
    {
      name: "FOG pant",
      category: "Pants",
      image: "/images/09.jpg",
      price: 4200000,
      countInStock: 10,
      brand: "FOG",
      rating: 5,
      numReviews: 10,
      description: "high quality product",
      quanSold: 5,
      size: ["XL", "L", "M", "S"],
      discount: 10,
      colors: ["red", "black", "blue", "grey"],
    },
    {
      name: "Nike Paranoise",
      category: "Shoes",
      image: "/images/01.jpg",
      price: 17000000,
      countInStock: 10,
      brand: "Nike",
      rating: 5,
      numReviews: 10,
      description: "high quality product",
      quanSold: 5,
      size: ["8", "9", "5", "7"],
      discount: 10,
      colors: ["red", "black", "blue", "grey"],
    },
    {
      name: "Converse FOG",
      category: "Shoes",
      image: "/images/02.jpg",
      price: 5000000,
      countInStock: 10,
      brand: "Converse",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      quanSold: 5,
      size: ["8", "9", "5", "7"],
      discount:10,
      colors: [ "black", "white", "grey"],
    },
    {
      name: "HypeBeast",
      category: "Toys",
      image: "/images/03.jpg",
      price: 10000000,
      countInStock: 10,
      brand: "Bape",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      quanSold: 5,
      size: [ "100"],
      discount: 10,
      colors: [ "black", "grey"],
    },
    {
      name: "Tee Champion",
      category: "Shirts",
      image: "/images/10.jpg",
      price: 200000,
      countInStock: 10,
      brand: "Champion",
      rating: 3.5,
      numReviews: 10,
      description: "high quality product",
      quanSold: 5,
      size: [ "M","XL"],
      discount: 10,
      colors: [ "black", "grey"],
    },
    {
      name: "Tee Carthartt",
      category: "Shirts",
      image: "/images/11.jpg",
      price: 300000,
      countInStock: 10,
      brand: "Carthartt",
      rating: 1.5,
      numReviews: 10,
      description: "high quality product",
      quanSold: 5,
      size: [ "S"],
      discount: 10,
      colors: [ "black", "grey"],
    },
    {
      name: "Tee Thrasher",
      category: "Shirts",
      image: "/images/12.jpg",
      price: 400000,
      countInStock: 10,
      brand: "Thrasher",
      rating: 2.5,
      numReviews: 10,
      description: "high quality product",
      quanSold: 5,
      size: [ "L","M"],
      discount: 10,
      colors: [ "black", "grey"],
    },
  ],
};
export default data;
